#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 30 06:11:48 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}